# -*- coding: utf-8 -*-
"""ml_Extra_Tree .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19wdhZsHyfpYER9nfdXsfYHKK0vEBnQsP
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib

from keras import models
from keras import layers
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.metrics import classification_report
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.datasets import make_classification
from scipy.stats import skew
from scipy.stats import kurtosis

pd.set_option('display.max_rows',None)

def load_variables(feature6):
    ### 輸入對數轉換後的資料

    x_test = pd.read_csv('testx_210904.csv',header=0)
    y_test = pd.read_csv('testy_210904.csv',header=0)
    x_train = pd.read_csv('trainx_210904.csv',header=0)
    y_train = pd.read_csv('trainy_210904.csv',header=0)

    #C45 交集 特徵（Random Forest＋逐步特徵消除)的 6 欄位
    x_test = x_test.loc[:,['workplaces_km', 'area_m', 'nuclear_reactor_km', 'sub_area_id', 'catering_km', 'mosque_km']]
    x_train = x_train.loc[:,['workplaces_km', 'area_m', 'nuclear_reactor_km', 'sub_area_id', 'catering_km', 'mosque_km']]

    """# ExtraTrees 抽取不放回"""
    ETreec = ExtraTreesClassifier()
    ETreec.fit(x_train, y_train) #訓練資料
    ETree_pred=ETreec.predict(x_test) #測試資料
    
    """# Save Model Using joblib"""
    joblib.dump(ETreec, 'Cafe_model')

    loaded_model = joblib.load('Cafe_model')
    #return loaded_model
    result = loaded_model.predict(np.array([feature6]))
    #result = loaded_model.predict(np.array([[2.069721,17.079556,2.786497,91,-0.806710,0.651145]]))


    ###最終y=8級
    #0eco,0 abbr,0 top ->1 都沒有咖啡廳
    #1,0,0 ->2 只有eco
    #0,1,0 ->3 只有小資
    #0,0,1 ->4 只有高檔
    #1,1,0 ->5 有小資與eco
    #1,0,1 ->6 有高檔與eco
    #0,1,1 ->7 有高檔與小資
    #1,1,1 ->8 三個都有

    return result
